(window.webpackJsonp=window.webpackJsonp||[]).push([[19],{75:function(e,n,a){"use strict";a.r(n),a.d(n,"frontMatter",(function(){return l})),a.d(n,"metadata",(function(){return s})),a.d(n,"rightToc",(function(){return b})),a.d(n,"default",(function(){return u}));var t=a(2),r=a(6),o=(a(0),a(78)),i=a(96),c=a(97),l={id:"can-catch",title:"CanCatch - Scalaz"},s={unversionedId:"scalaz-effect/can-catch",id:"scalaz-effect/can-catch",isDocsHomePage:!1,title:"CanCatch - Scalaz",description:"CanCatch",source:"@site/../generated-docs/target/mdoc/scalaz-effect/can-catch.md",slug:"/scalaz-effect/can-catch",permalink:"/docs/scalaz-effect/can-catch",version:"current",sidebar:"someSidebar",previous:{title:"EffectConstructor - Scalaz",permalink:"/docs/scalaz-effect/effect-constructor"},next:{title:"OptionTSupport - Scalaz",permalink:"/docs/scalaz-effect/optiont-support"}},b=[{value:"CanCatch",id:"cancatch",children:[]},{value:"CanCatch.catchNonFatal",id:"cancatchcatchnonfatal",children:[{value:"How to Use",id:"how-to-use",children:[]},{value:"Happy Path Example",id:"happy-path-example",children:[]},{value:"Unhappy Path Example",id:"unhappy-path-example",children:[]}]},{value:"CanCatch.catchNonFatalEither",id:"cancatchcatchnonfataleither",children:[{value:"How to Use",id:"how-to-use-1",children:[]},{value:"Happy Path Example",id:"happy-path-example-1",children:[]},{value:"Unhappy Path Example",id:"unhappy-path-example-1",children:[]}]},{value:"CanCatch.catchNonFatalEitherT",id:"cancatchcatchnonfataleithert",children:[{value:"How to Use",id:"how-to-use-2",children:[]},{value:"Happy Path Example",id:"happy-path-example-2",children:[]},{value:"Unhappy Path Example",id:"unhappy-path-example-2",children:[]}]},{value:"Catching",id:"catching",children:[]},{value:"Catching.catchNonFatal",id:"catchingcatchnonfatal",children:[{value:"How to Use",id:"how-to-use-3",children:[]},{value:"Happy Path Example",id:"happy-path-example-3",children:[]},{value:"Unhappy Path Example",id:"unhappy-path-example-3",children:[]}]},{value:"Catching.catchNonFatalEither",id:"catchingcatchnonfataleither",children:[{value:"How to Use",id:"how-to-use-4",children:[]},{value:"Happy Path Example",id:"happy-path-example-4",children:[]},{value:"Unhappy Path Example",id:"unhappy-path-example-4",children:[]}]},{value:"Catching.catchNonFatalEitherT",id:"catchingcatchnonfataleithert",children:[{value:"How to Use",id:"how-to-use-5",children:[]},{value:"Happy Path Example",id:"happy-path-example-5",children:[]},{value:"Unhappy Path Example",id:"unhappy-path-example-5",children:[]}]}],d={rightToc:b};function u(e){var n=e.components,a=Object(r.a)(e,["components"]);return Object(o.b)("wrapper",Object(t.a)({},d,a,{components:n,mdxType:"MDXLayout"}),Object(o.b)("h2",{id:"cancatch"},"CanCatch"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"CanCatch")," lets you catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," in the ",Object(o.b)("inlineCode",{parentName:"p"},"F[A]"),"\nand turned it into ",Object(o.b)("inlineCode",{parentName:"p"},"F[Either[Throwable, A]]"),". It takes a function from ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable"),"\nto your own error type, yet it can handle only ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ones as already mentioned."),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"trait CanCatch[F[_]] {\n  def catchNonFatal[A, B](fb: => F[B])(f: Throwable => A): F[A \\/ B]\n\n  def catchNonFatalEither[A, B](fab: => F[A \\/ B])(f: Throwable => A): F[A \\/ B]\n\n  def catchNonFatalEitherT[A, B](fab: => EitherT[F, A, B])(f: Throwable => A): EitherT[F, A, B]\n}\n")),Object(o.b)("h2",{id:"cancatchcatchnonfatal"},"CanCatch.catchNonFatal"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"CanCatch[F].catchNonFatal[A, B]")," lets you catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," from ",Object(o.b)("inlineCode",{parentName:"p"},"F[B]"),"\nand returns ",Object(o.b)("inlineCode",{parentName:"p"},"F[A \\/ B]"),"."),Object(o.b)("h3",{id:"how-to-use"},"How to Use"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz.effect._\n\nimport effectie.scalaz._\n\nval fa = CanCatch[IO].catchNonFatal(\n    IO(throw new RuntimeException(\"Something's wrong!\"))\n  )(identity)\n// fa: IO[scalaz.\\/[Throwable, Nothing]] = scalaz.effect.IO$$anon$7@15ee319f\n\nfa.unsafePerformIO()\n// res1: scalaz.\\/[Throwable, Nothing] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport effectie.scalaz._\n\nval executorService: ExecutorService = Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n// executorService: ExecutorService = java.util.concurrent.ForkJoinPool@294d82f6[Running, parallelism = 2, size = 2, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]\nimplicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n// ec: ExecutionContext = scala.concurrent.impl.ExecutionContextImpl$$anon$4@1b7f1184\n\nval fa = CanCatch[Future].catchNonFatal(\n    Future(throw new RuntimeException(\"Something's wrong!\"))\n  )(identity)\n// fa: Future[scalaz.\\/[Throwable, Nothing]] = Future(Success(-\\/(java.lang.RuntimeException: Something's wrong!)))\n\n// Just for this example, you wouldn't want to do it in your production code\nAwait.result(fa, Duration.Inf)\n// res3: scalaz.\\/[Throwable, Nothing] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\n\nCanCatch[Id].catchNonFatal(\n    throw new RuntimeException(\"Something's wrong!\")\n  )(identity)\n// res5: Throwable \\/ Nothing = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n")))),Object(o.b)("h3",{id:"happy-path-example"},"Happy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@534ef9a6\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = \\/-(b = 202)\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 202\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  }\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    CanCatch[F].catchNonFatal(\n      for {\n        a <- pureOf(n + 100)\n        b <- effectOf(doSomethingBad(a))\n      } yield b\n    )(MyError.nonFatalThrowable)\n\n  def main(arg: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// \\/-(202)\n// Result is 202\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](1)\n// fa: Id[MyError \\/ Int] = \\/-(b = 202)\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 202\n')))),Object(o.b)("h3",{id:"unhappy-path-example"},"Unhappy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\nif (n < 0)\n  throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\nelse\n  n * 2\n\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](-101)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@26ac7632\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n//   )\n// )\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  }\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    CanCatch[F].catchNonFatal(\n      for {\n        a <- pureOf(n + 100)\n        b <- effectOf(doSomethingBad(a))\n      } yield b\n    )(MyError.nonFatalThrowable)\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n\n    try {\n      val fa = doSomething[Future](-101)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// -\\/(NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]))\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1])\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](-101)\n// fa: Id[MyError \\/ Int] = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n//   )\n// )\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n')))),Object(o.b)("h2",{id:"cancatchcatchnonfataleither"},"CanCatch.catchNonFatalEither"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"CanCatch[F].catchNonFatalEither[A, B]")," lets you catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," from ",Object(o.b)("inlineCode",{parentName:"p"},"F[A \\/ B]"),"\nand returns ",Object(o.b)("inlineCode",{parentName:"p"},"F[A \\/ B]"),"."),Object(o.b)("h3",{id:"how-to-use-1"},"How to Use"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\n\nval fa = CanCatch[IO].catchNonFatalEither(\n    IO((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int)\n  )(identity)\n// fa: IO[Throwable \\/ Int] = scalaz.effect.IO$$anon$7@626c2597\n\nfa.unsafePerformIO()\n// res19: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\n\nimport effectie.scalaz._\n\nval executorService: ExecutorService = Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n// executorService: ExecutorService = java.util.concurrent.ForkJoinPool@85c77aa[Running, parallelism = 2, size = 2, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]\nimplicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n// ec: ExecutionContext = scala.concurrent.impl.ExecutionContextImpl$$anon$4@b9fabab\n\nval fa = CanCatch[Future].catchNonFatalEither(\n    Future((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int)\n  )(identity)\n// fa: Future[Throwable \\/ Int] = Future(Success(-\\/(java.lang.RuntimeException: Something's wrong!)))\n\n// Just for this example, you wouldn't want to do it in your production code\nAwait.result(fa, Duration.Inf)\n// res21: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\n\nCanCatch[Id].catchNonFatalEither(\n    (throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int\n  )(identity)\n// res23: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n")))),Object(o.b)("h3",{id:"happy-path-example-1"},"Happy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@504be8f2\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = \\/-(b = 200)\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n\n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n  \n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    CanCatch[F].catchNonFatalEither(\n      for {\n        aOrB <- pureOf(divide100By(n))\n        c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n      } yield c\n    )(MyError.nonFatalThrowable)\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n\n    try {\n      val fa = doSomething[Future](1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// \\/-(200)\n// Result is 200\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](1)\n// fa: Id[MyError \\/ Int] = \\/-(b = 200)\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n')))),Object(o.b)("h3",{id:"unhappy-path-example-1"},"Unhappy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\nif (n < 0)\n  throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\nelse\n  n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](-1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@298fb93\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n    \n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    CanCatch[F].catchNonFatalEither(\n      for {\n        aOrB <- pureOf(divide100By(n))\n        c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n      } yield c\n    )(MyError.nonFatalThrowable)\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](-1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// -\\/(NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]))\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](-1)\n// fa: Id[MyError \\/ Int] = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n')))),Object(o.b)("h2",{id:"cancatchcatchnonfataleithert"},"CanCatch.catchNonFatalEitherT"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"CanCatch[F].catchNonFatalEitherT[A, B]")," lets you catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," from ",Object(o.b)("inlineCode",{parentName:"p"},"EitherT[F, A, B]"),"\nand returns ",Object(o.b)("inlineCode",{parentName:"p"},"EitherT[F, A, B]"),"."),Object(o.b)("h3",{id:"how-to-use-2"},"How to Use"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\n\nval fa = CanCatch[IO].catchNonFatalEitherT(\n    EitherT(IO((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int))\n  )(identity)\n// fa: EitherT[IO, Throwable, Int] = EitherT(\n//   run = scalaz.effect.IO$$anon$7@1bc57080\n// )\n\nfa.run.unsafePerformIO()\n// res37: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport effectie.scalaz._\n\nval executorService: ExecutorService = Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n// executorService: ExecutorService = java.util.concurrent.ForkJoinPool@284d41f[Running, parallelism = 2, size = 2, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]\nimplicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n// ec: ExecutionContext = scala.concurrent.impl.ExecutionContextImpl$$anon$4@3275f5bf\n\nval fa = CanCatch[Future].catchNonFatalEitherT(\n    EitherT(Future((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int))\n  )(identity)\n// fa: EitherT[Future, Throwable, Int] = EitherT(\n//   run = Future(Success(-\\/(java.lang.RuntimeException: Something's wrong!)))\n// )\n\n// Just for this example, you wouldn't want to do it in your production code\nAwait.result(fa.run, Duration.Inf)\n// res39: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\n\nval fa = CanCatch[Id].catchNonFatalEitherT(\n    EitherT((throw new RuntimeException(\"Something's wrong!\")): Id[Throwable \\/ Int])\n  )(identity)\n// fa: EitherT[Id, Throwable, Int] = EitherT(\n//   run = -\\/(a = java.lang.RuntimeException: Something's wrong!)\n// )\n\nfa.run\n// res41: Id[Throwable \\/ Int] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n")))),Object(o.b)("h3",{id:"happy-path-example-2"},"Happy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[IO](1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@500105ac\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = \\/-(b = 200)\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.EitherTSupport._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n    \n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    CanCatch[F].catchNonFatalEitherT(\n      for {\n        b <- EitherT(pureOf(divide100By(n)))\n        c <- eitherTRight[MyError](doSomethingBad(b))\n      } yield c\n    )(MyError.nonFatalThrowable).run\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// \\/-(200)\n// Result is 200\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[Id](1)\n// fa: Id[MyError \\/ Int] = \\/-(b = 200)\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n')))),Object(o.b)("h3",{id:"unhappy-path-example-2"},"Unhappy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.EitherTSupport._\nimport effectie.scalaz.Effectful._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\nif (n < 0)\n  throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\nelse\n  n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[IO](-1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@5101651b\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.EitherTSupport._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n    \n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    CanCatch[F].catchNonFatalEitherT(\n      for {\n        b <- EitherT(pureOf(divide100By(n)))\n        c <- eitherTRight[MyError](doSomethingBad(b))\n      } yield c\n    )(MyError.nonFatalThrowable).run\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](-1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// -\\/(NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]))\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  CanCatch[F].catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[Id](-1)\n// fa: Id[MyError \\/ Int] = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n')))),Object(o.b)("h2",{id:"catching"},"Catching"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"Catching.catchNonFatal")," provides a convenient way to use ",Object(o.b)("inlineCode",{parentName:"p"},"CanCatch")," to catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," in the ",Object(o.b)("inlineCode",{parentName:"p"},"F[A]"),"\nand turned it into ",Object(o.b)("inlineCode",{parentName:"p"},"F[Either[Throwable, A]]"),". Just like ",Object(o.b)("inlineCode",{parentName:"p"},"CanCatch"),", it takes a function from ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable"),"\nto your own error type, yet it can handle only ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ones as already mentioned."),Object(o.b)("h2",{id:"catchingcatchnonfatal"},"Catching.catchNonFatal"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"catchNonFatal")," lets you catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," from ",Object(o.b)("inlineCode",{parentName:"p"},"F[B]"),"\nand returns ",Object(o.b)("inlineCode",{parentName:"p"},"F[A \\/ B]"),"."),Object(o.b)("h3",{id:"how-to-use-3"},"How to Use"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz.effect._\n\nimport effectie.scalaz.Catching._\n\nval fa = catchNonFatal(\n    IO((throw new RuntimeException(\"Something's wrong!\")): Int)\n  )(identity)\n// fa: IO[scalaz.\\/[Throwable, Int]] = scalaz.effect.IO$$anon$7@76fae044\n\nfa.unsafePerformIO()\n// res55: scalaz.\\/[Throwable, Int] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport effectie.scalaz.Catching._\n\nval executorService: ExecutorService = Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n// executorService: ExecutorService = java.util.concurrent.ForkJoinPool@45e3a111[Running, parallelism = 2, size = 2, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]\nimplicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n// ec: ExecutionContext = scala.concurrent.impl.ExecutionContextImpl$$anon$4@64ba8129\n\nval fa = catchNonFatal(\n    Future(throw new RuntimeException(\"Something's wrong!\"))\n  )(identity)\n// fa: Future[scalaz.\\/[Throwable, Nothing]] = Future(Success(-\\/(java.lang.RuntimeException: Something's wrong!)))\n\n// Just for this example, you wouldn't want to do it in your production code\nAwait.result(fa, Duration.Inf)\n// res57: scalaz.\\/[Throwable, Nothing] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz.Catching._\n\ncatchNonFatal[Id](\n    throw new RuntimeException(\"Something's wrong!\")\n  )(identity)\n// res59: Id[Throwable \\/ Nothing] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n")))),Object(o.b)("h3",{id:"happy-path-example-3"},"Happy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@3a47e4aa\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = \\/-(b = 202)\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 202\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  }\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    catchNonFatal(\n      for {\n        a <- pureOf(n + 100)\n        b <- effectOf(doSomethingBad(a))\n      } yield b\n    )(MyError.nonFatalThrowable)\n\n  def main(arg: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// \\/-(202)\n// Result is 202\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](1)\n// fa: Id[MyError \\/ Int] = \\/-(b = 202)\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 202\n')))),Object(o.b)("h3",{id:"unhappy-path-example-3"},"Unhappy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\nif (n < 0)\n  throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\nelse\n  n * 2\n\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](-101)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@591336bc\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n//   )\n// )\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  }\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    catchNonFatal(\n      for {\n        a <- pureOf(n + 100)\n        b <- effectOf(doSomethingBad(a))\n      } yield b\n    )(MyError.nonFatalThrowable)\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n\n    try {\n      val fa = doSomething[Future](-101)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// -\\/(NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]))\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1])\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n}\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatal(\n    for {\n      a <- pureOf(n + 100)\n      b <- effectOf(doSomethingBad(a))\n    } yield b\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](-101)\n// fa: Id[MyError \\/ Int] = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n//   )\n// )\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(MyError.NonFatalThrowable(a)) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with java.lang.IllegalArgumentException: n cannot be a negative number. [n: -1]\n')))),Object(o.b)("h2",{id:"catchingcatchnonfataleither"},"Catching.catchNonFatalEither"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"Catching.catchNonFatalEither")," provides a convenient way to use ",Object(o.b)("inlineCode",{parentName:"p"},"CanCatch"),"\nto catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," from ",Object(o.b)("inlineCode",{parentName:"p"},"F[A \\/ B]")," and returns ",Object(o.b)("inlineCode",{parentName:"p"},"F[A \\/ B]"),"."),Object(o.b)("h3",{id:"how-to-use-4"},"How to Use"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz.Catching._\n\nval fa = catchNonFatalEither(\n    IO((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int)\n  )(identity)\n// fa: IO[Throwable \\/ Int] = scalaz.effect.IO$$anon$7@59ee88f7\n\nfa.unsafePerformIO()\n// res73: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\n\nimport effectie.scalaz.Catching._\n\nval executorService: ExecutorService = Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n// executorService: ExecutorService = java.util.concurrent.ForkJoinPool@71e160e4[Running, parallelism = 2, size = 2, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]\nimplicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n// ec: ExecutionContext = scala.concurrent.impl.ExecutionContextImpl$$anon$4@5ce5e71f\n\nval fa = catchNonFatalEither(\n    Future((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int)\n  )(identity)\n// fa: Future[Throwable \\/ Int] = Future(Success(-\\/(java.lang.RuntimeException: Something's wrong!)))\n\n// Just for this example, you wouldn't want to do it in your production code\nAwait.result(fa, Duration.Inf)\n// res75: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz.Catching._\n\ncatchNonFatalEither[Id](\n    (throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int\n  )(identity)\n// res77: Id[Throwable \\/ Int] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n")))),Object(o.b)("h3",{id:"happy-path-example-4"},"Happy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@6f99bd50\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = \\/-(b = 200)\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n\n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n  \n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    catchNonFatalEither(\n      for {\n        aOrB <- pureOf(divide100By(n))\n        c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n      } yield c\n    )(MyError.nonFatalThrowable)\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n\n    try {\n      val fa = doSomething[Future](1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// \\/-(200)\n// Result is 200\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](1)\n// fa: Id[MyError \\/ Int] = \\/-(b = 200)\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n')))),Object(o.b)("h3",{id:"unhappy-path-example-4"},"Unhappy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\nif (n < 0)\n  throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\nelse\n  n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[IO](-1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@4f425a34\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n    \n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    catchNonFatalEither(\n      for {\n        aOrB <- pureOf(divide100By(n))\n        c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n      } yield c\n    )(MyError.nonFatalThrowable)\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](-1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// -\\/(NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]))\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEither(\n    for {\n      aOrB <- pureOf(divide100By(n))\n      c <- effectOf(aOrB.map(b => doSomethingBad(b)))\n    } yield c\n  )(MyError.nonFatalThrowable)\n\nval fa = doSomething[Id](-1)\n// fa: Id[MyError \\/ Int] = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n')))),Object(o.b)("h2",{id:"catchingcatchnonfataleithert"},"Catching.catchNonFatalEitherT"),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"Catching.catchNonFatalEitherT")," provides a convenient way to use ",Object(o.b)("inlineCode",{parentName:"p"},"CanCatch"),"\nto catch ",Object(o.b)("inlineCode",{parentName:"p"},"NonFatal")," ",Object(o.b)("inlineCode",{parentName:"p"},"Throwable")," from ",Object(o.b)("inlineCode",{parentName:"p"},"EitherT[F, A, B]")," and returns ",Object(o.b)("inlineCode",{parentName:"p"},"EitherT[F, A, B]"),"."),Object(o.b)("h3",{id:"how-to-use-5"},"How to Use"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz.Catching._\n\nval fa = catchNonFatalEitherT[IO](\n    EitherT(IO((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int))\n  )(identity)\n// fa: EitherT[IO, Throwable, Int] = EitherT(\n//   run = scalaz.effect.IO$$anon$7@28ce59a5\n// )\n\nfa.run.unsafePerformIO()\n// res91: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\n\nimport effectie.scalaz.Catching._\n\nval executorService: ExecutorService = Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n// executorService: ExecutorService = java.util.concurrent.ForkJoinPool@741b6f71[Running, parallelism = 2, size = 2, active = 0, running = 0, steals = 1, tasks = 0, submissions = 0]\nimplicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n// ec: ExecutionContext = scala.concurrent.impl.ExecutionContextImpl$$anon$4@2ec20326\n\nval fa = catchNonFatalEitherT[Future](\n    EitherT(Future((throw new RuntimeException(\"Something's wrong!\")): Throwable \\/ Int))\n  )(identity)\n// fa: EitherT[Future, Throwable, Int] = EitherT(\n//   run = Future(Success(-\\/(java.lang.RuntimeException: Something's wrong!)))\n// )\n\n// Just for this example, you wouldn't want to do it in your production code\nAwait.result(fa.run, Duration.Inf)\n// res93: Throwable \\/ Int = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n"))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),"import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz.Catching._\n\nval fa = catchNonFatalEitherT[Id](\n    EitherT((throw new RuntimeException(\"Something's wrong!\")): Id[Throwable \\/ Int])\n  )(identity)\n// fa: EitherT[Id, Throwable, Int] = EitherT(\n//   run = -\\/(a = java.lang.RuntimeException: Something's wrong!)\n// )\n\nfa.run\n// res95: Id[Throwable \\/ Int] = -\\/(\n//   a = java.lang.RuntimeException: Something's wrong!\n// )\n")))),Object(o.b)("h3",{id:"happy-path-example-5"},"Happy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[IO](1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@6d7ec6fd\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = \\/-(b = 200)\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.scalaz.EitherTSupport._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n    \n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    catchNonFatalEitherT(\n      for {\n        b <- EitherT(pureOf(divide100By(n)))\n        c <- eitherTRight[MyError](doSomethingBad(b))\n      } yield c\n    )(MyError.nonFatalThrowable).run\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// \\/-(200)\n// Result is 200\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[Id](1)\n// fa: Id[MyError \\/ Int] = \\/-(b = 200)\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result is 200\n')))),Object(o.b)("h3",{id:"unhappy-path-example-5"},"Unhappy Path Example"),Object(o.b)(i.a,{groupId:"effects",defaultValue:"io",values:[{label:"IO",value:"io"},{label:"Future",value:"future"},{label:"Id",value:"id"}],mdxType:"Tabs"},Object(o.b)(c.a,{value:"io",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\nimport scalaz.effect._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\nif (n < 0)\n  throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\nelse\n  n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[IO](-1)\n// fa: IO[MyError \\/ Int] = scalaz.effect.IO$$anon$7@1d8f2330\nval result = fa.unsafePerformIO()\n// result: MyError \\/ Int = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nresult match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"future",mdxType:"TabItem"},Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import java.util.concurrent.{ExecutorService, Executors}\nimport scala.concurrent.{ExecutionContext, Future, Await}\nimport scala.concurrent.duration._\n\nimport scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.scalaz.EitherTSupport._\nimport effectie.concurrent.ExecutorServiceOps\n\nobject MyApp {\n  sealed trait MyError\n  object MyError {\n    final case class NonFatalThrowable(throwable: Throwable) extends MyError\n    case object DivideByZero extends MyError\n    \n    def nonFatalThrowable(throwable: Throwable): MyError\n      = NonFatalThrowable(throwable)\n  \n    def divideByZero: MyError = DivideByZero\n  }\n\n  def divide100By(n: Int): MyError \\/ Int =\n    if (n === 0)\n      MyError.divideByZero.left[Int]\n    else\n      (100 / n).right[MyError]\n\n  def doSomethingBad(n: Int): Int =\n    if (n < 0)\n      throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n    else\n      n * 2\n\n  def doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n    n: Int\n  ): F[MyError \\/ Int] =\n    catchNonFatalEitherT(\n      for {\n        b <- EitherT(pureOf(divide100By(n)))\n        c <- eitherTRight[MyError](doSomethingBad(b))\n      } yield c\n    )(MyError.nonFatalThrowable).run\n\n  def main(args: Array[String]): Unit = {\n    val executorService: ExecutorService =\n      Executors.newWorkStealingPool(Runtime.getRuntime.availableProcessors())\n    implicit val ec: ExecutionContext = ExecutionContext.fromExecutorService(executorService)\n    \n    try {\n      val fa = doSomething[Future](-1)\n      println(fa)\n      val result = Await.result(fa, 1.second)\n      println(result)\n      result match {\n        case \\/-(b) =>\n          println(s"Result is $b")\n        case -\\/(a) =>\n          println(s"Result: Failed with $a")\n      }\n    } finally {\n      ExecutorServiceOps.shutdownAndAwaitTermination(executorService, 1.second)\n    }\n  }\n}\nMyApp.main(Array.empty)\n// Future(<not completed>)\n// -\\/(NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]))\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n'))),Object(o.b)(c.a,{value:"id",mdxType:"TabItem"},Object(o.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(t.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(t.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(o.b)("path",Object(t.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"NOTE")),Object(o.b)("div",Object(t.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"Use of ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," is not recommended as ",Object(o.b)("inlineCode",{parentName:"p"},"Id")," means having no ",Object(o.b)("inlineCode",{parentName:"p"},"Effect"),". Use it only for some special cases like testing."))),Object(o.b)("pre",null,Object(o.b)("code",Object(t.a)({parentName:"pre"},{className:"language-scala"}),'import scalaz._\nimport Scalaz._\n\nimport effectie.scalaz._\nimport effectie.scalaz.Effectful._\nimport effectie.scalaz.Catching._\nimport effectie.scalaz.EitherTSupport._\n\nsealed trait MyError\nobject MyError {\n  final case class NonFatalThrowable(throwable: Throwable) extends MyError\n  case object DivideByZero extends MyError\n  \n  def nonFatalThrowable(throwable: Throwable): MyError\n    = NonFatalThrowable(throwable)\n\n  def divideByZero: MyError = DivideByZero\n}\n\ndef divide100By(n: Int): MyError \\/ Int =\n  if (n === 0)\n    MyError.divideByZero.left[Int]\n  else\n    (100 / n).right[MyError]\n\ndef doSomethingBad(n: Int): Int =\n  if (n < 0)\n    throw new IllegalArgumentException(s"n cannot be a negative number. [n: $n]")\n  else\n    n * 2\n\ndef doSomething[F[_]: EffectConstructor: CanCatch: Monad](\n  n: Int\n): F[MyError \\/ Int] =\n  catchNonFatalEitherT(\n    for {\n      b <- EitherT(pureOf(divide100By(n)))\n      c <- eitherTRight[MyError](doSomethingBad(b))\n    } yield c\n  )(MyError.nonFatalThrowable).run\n\nval fa = doSomething[Id](-1)\n// fa: Id[MyError \\/ Int] = -\\/(\n//   a = NonFatalThrowable(\n//     throwable = java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100]\n//   )\n// )\nfa match {\n  case \\/-(b) =>\n    println(s"Result is $b")\n  case -\\/(a) =>\n    println(s"Result: Failed with $a")\n}\n// Result: Failed with NonFatalThrowable(java.lang.IllegalArgumentException: n cannot be a negative number. [n: -100])\n')))))}u.isMDXComponent=!0},78:function(e,n,a){"use strict";a.d(n,"a",(function(){return d})),a.d(n,"b",(function(){return p}));var t=a(0),r=a.n(t);function o(e,n,a){return n in e?Object.defineProperty(e,n,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[n]=a,e}function i(e,n){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var t=Object.getOwnPropertySymbols(e);n&&(t=t.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),a.push.apply(a,t)}return a}function c(e){for(var n=1;n<arguments.length;n++){var a=null!=arguments[n]?arguments[n]:{};n%2?i(Object(a),!0).forEach((function(n){o(e,n,a[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):i(Object(a)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(a,n))}))}return e}function l(e,n){if(null==e)return{};var a,t,r=function(e,n){if(null==e)return{};var a,t,r={},o=Object.keys(e);for(t=0;t<o.length;t++)a=o[t],n.indexOf(a)>=0||(r[a]=e[a]);return r}(e,n);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(t=0;t<o.length;t++)a=o[t],n.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(r[a]=e[a])}return r}var s=r.a.createContext({}),b=function(e){var n=r.a.useContext(s),a=n;return e&&(a="function"==typeof e?e(n):c(c({},n),e)),a},d=function(e){var n=b(e.components);return r.a.createElement(s.Provider,{value:n},e.children)},u={inlineCode:"code",wrapper:function(e){var n=e.children;return r.a.createElement(r.a.Fragment,{},n)}},m=r.a.forwardRef((function(e,n){var a=e.components,t=e.mdxType,o=e.originalType,i=e.parentName,s=l(e,["components","mdxType","originalType","parentName"]),d=b(a),m=t,p=d["".concat(i,".").concat(m)]||d[m]||u[m]||o;return a?r.a.createElement(p,c(c({ref:n},s),{},{components:a})):r.a.createElement(p,c({ref:n},s))}));function p(e,n){var a=arguments,t=n&&n.mdxType;if("string"==typeof e||t){var o=a.length,i=new Array(o);i[0]=m;var c={};for(var l in n)hasOwnProperty.call(n,l)&&(c[l]=n[l]);c.originalType=e,c.mdxType="string"==typeof e?e:t,i[1]=c;for(var s=2;s<o;s++)i[s]=a[s];return r.a.createElement.apply(null,i)}return r.a.createElement.apply(null,a)}m.displayName="MDXCreateElement"},79:function(e,n,a){"use strict";function t(e){var n,a,r="";if("string"==typeof e||"number"==typeof e)r+=e;else if("object"==typeof e)if(Array.isArray(e))for(n=0;n<e.length;n++)e[n]&&(a=t(e[n]))&&(r&&(r+=" "),r+=a);else for(n in e)e[n]&&(r&&(r+=" "),r+=n);return r}n.a=function(){for(var e,n,a=0,r="";a<arguments.length;)(e=arguments[a++])&&(n=t(e))&&(r&&(r+=" "),r+=n);return r}},87:function(e,n,a){"use strict";var t=a(0),r=a(88);n.a=function(){var e=Object(t.useContext)(r.a);if(null==e)throw new Error("`useUserPreferencesContext` is used outside of `Layout` Component.");return e}},88:function(e,n,a){"use strict";var t=a(0),r=Object(t.createContext)(void 0);n.a=r},96:function(e,n,a){"use strict";var t=a(0),r=a.n(t),o=a(87),i=a(79),c=a(46),l=a.n(c),s=37,b=39;n.a=function(e){var n=e.block,a=e.children,c=e.defaultValue,d=e.values,u=e.groupId,m=e.className,p=Object(o.a)(),h=p.tabGroupChoices,f=p.setTabGroupChoices,v=Object(t.useState)(c),g=v[0],E=v[1],w=Object(t.useState)(!1),y=w[0],O=w[1];if(null!=u){var j=h[u];null!=j&&j!==g&&d.some((function(e){return e.value===j}))&&E(j)}var x=function(e){E(e),null!=u&&f(u,e)},N=[],I=function(e){e.metaKey||e.altKey||e.ctrlKey||O(!0)},T=function(){O(!1)};return Object(t.useEffect)((function(){return window.addEventListener("keydown",I),window.addEventListener("mousedown",T),function(){window.removeEventListener("keydown",I),window.removeEventListener("mousedown",T)}}),[]),r.a.createElement("div",null,r.a.createElement("ul",{role:"tablist","aria-orientation":"horizontal",className:Object(i.a)("tabs",{"tabs--block":n},m)},d.map((function(e){var n=e.value,a=e.label;return r.a.createElement("li",{role:"tab",tabIndex:0,"aria-selected":g===n,className:Object(i.a)("tabs__item",l.a.tabItem,{"tabs__item--active":g===n}),style:y?{}:{outline:"none"},key:n,ref:function(e){return N.push(e)},onKeyDown:function(e){!function(e,n,a){switch(a.keyCode){case b:!function(e,n){var a=e.indexOf(n)+1;e[a]?e[a].focus():e[0].focus()}(e,n);break;case s:!function(e,n){var a=e.indexOf(n)-1;e[a]?e[a].focus():e[e.length-1].focus()}(e,n)}}(N,e.target,e),I(e)},onFocus:function(){return x(n)},onClick:function(){x(n),O(!1)},onPointerDown:function(){return O(!1)}},a)}))),r.a.createElement("div",{role:"tabpanel",className:"margin-vert--md"},t.Children.toArray(a).filter((function(e){return e.props.value===g}))[0]))}},97:function(e,n,a){"use strict";var t=a(0),r=a.n(t);n.a=function(e){return r.a.createElement("div",null,e.children)}}}]);